# Generated by Django 4.0.3 on 2022-04-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=200)),
                ('isbn', models.IntegerField()),
                ('author_name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=200)),
                ('edition', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=30)),
                ('ISBN', models.IntegerField()),
                ('issuedate', models.DateField(auto_now=True)),
                ('publication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecords',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('book_name', models.CharField(max_length=300)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
    ]
