# Generated by Django 4.0.3 on 2022-04-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('book_name', models.CharField(max_length=300)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentRecords',
        ),
    ]
